#!/bin/bash

function f_users {
  SCRIPT_COUNT=1
  echo "[$SCRIPT_COUNT] Remove users"

  for user in games gnats irc list news sync uucp; do
      userdel -r "$user" 2>/dev/null
  done
  ((SCRIPT_COUNT++))
}
